### PR TITLE
Tests with sqlite in-memory

### PR DESCRIPTION
**Pull request by CyberiaResurrection**
No direct bug fixes here, but laying the ground work to easily write (and use) more comprehensive and aggressive tests.  As a nice side effect, migrations and seeds get a workout with each test run.

The immediate use case I had in mind when making these changes was tackling #95, since that looks like it might need a functional test to fully characterise underlying issue - I have no doubt blank first and/or last name is part of issue, but it might not be all of it.

### CODE REVIEW

**Comment by chintanbanugaria** [comment]
@CyberiaResurrection You have changed the default DB to sqlite. Is it working for you with left and inner joins with tables ?

**Comment by CyberiaResurrection** [comment]
I haven't changed the default for production - that remains at whatever has already been set (currently mysql), only for running tests.

Give me a bit and I'll push up a test case.

**Comment by CyberiaResurrection** [comment]
As promised, a test case illustrating how to do a basic join using Laravel's database abstraction layer.

**Comment by CyberiaResurrection** [comment]
Sorry, that was a rather long-winded way of saying yes, they work.  I was also trying to give you a way to independently check that joins work.

**Comment by CyberiaResurrection** [comment]
Is there anything else you want me to provide?

**Pull request merged**
